### ISSUE TITLE
Dictionary not found

### ISSUE THREAD

**Issue by davidhealey** [orbitalquark/textadept-spellcheck#1]
I see this message when I open TextAdept
`.textadept/modules/spellcheck/init.lua:118: Language not found: en_GB`

I have placed the en_GB hunspell file in *~/.textadept/dictionaries/*

I also don't see a spelling option in the Tools menu. This happens with both v10.8 and nightly.

**Comment by orbitalquark** [comment]
> I see this message when I open TextAdept
> `.textadept/modules/spellcheck/init.lua:118: Language not found: en_GB`
>
> I have placed the en_GB hunspell file in *~/.textadept/dictionaries/*

Did you also place the *.aff* file in addition to the *.dic* file?

> I also don't see a spelling option in the Tools menu. This happens with both v10.8 and nightly.

This module only works with 11.0 beta 2 or a recent 11.0 beta nightly.

**Comment by davidhealey** [comment]
I placed the .aff file alongside the .dic file. If I remove the dictionaries directory completely I get the same message in TextAdept instead of it falling back to its default.

I'm using 11.0 beta 2, according to the About window. I'm using the AppImage.

**Comment by orbitalquark** [comment]
> I placed the .aff file alongside the .dic file. If I remove the dictionaries directory completely I get the same message in TextAdept instead of it falling back to its default.

Instead of placing dictionaries in *~/.textadept/dictionaries/*, place them in *~/.textadept/modules/spellcheck/*. Textadept looks for Hunspell dictionaries there. I was able to do this with an en_GB dictionary downloaded from https://cgit.freedesktop.org/libreoffice/dictionaries/tree/en

> I'm using 11.0 beta 2, according to the About window. I'm using the AppImage.

What is "AppImage"?

**Comment by davidhealey** [comment]
Yeah that worked, thanks! 

I made a mistake when I said AppImage, I meant I was using the precompiled binary as opposed to compiling it myself.
