### ISSUE TITLE
Lua line 53 error

### ISSUE THREAD

**Issue by robotamer** [orbitalquark/textadept-spellcheck#2]
`.textadept/modules/spellcheck/init.lua:53: attempt to call a nil value (field 'new_indic_number')`

**Comment by orbitalquark** [comment]
If you are using Textadept 11.4 or earlier, please go to 
https://github.com/orbitalquark/textadept-spellcheck/releases and 
download the correct zip. The latest release is for 12.0 nightly and is 
not compatible with 11.4 or earlier.

Sorry for the confusion.

**Comment by robotamer** [comment]
That is right. I am using the [Void pkgs](https://github.com/void-linux/void-packages/tree/master/srcpkgs/textadept). I just switched to void so haven't yet checked in on how to make changes to the package source.
Thanks for the help, hopefully someone will update Void soon, meanwhile I will disable the spellchecker.
